version: 2
jobs:
  build:
    working_directory: ~/home/compliance
    docker:
      - image: bitexla/compliance_web
        environment:
          RAILS_ENV: test
          MYSQL_USERNAME: root
          MYSQL_HOST: localhost
          MYSQL_PASSWORD: example
          MYSQL_PORT: 3306
          REDIS_HOST: redis
          REDIS_PORT: 6379
      - image: circle/mysql
        environment:
          MYSQL_ROOT_PASSWORD: example
          MYSQL_USER: root
          MYSQL_HOST: 127.0.0.1
          MYSQL_ROOT_HOST: %
      - image: redis
    steps:
      - checkout
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run: bundle install --path vendor/bundle
      - run: bundle exec rails db:create db:schema:load db:migrate
      - run: bundle exec rspec

    