version: 2
jobs:
  build:
    working_directory: ~/home/compliance
    docker:
      - image: bitexla/compliance_web
        environment:
          RAILS_ENV: development
          MYSQL_USERNAME: root
          MYSQL_HOST: localhost
          MYSQL_PASSWORD: example
          REDIS_HOST: redis
          REDIS_PORT: 6379
      - image: mysql
        environment:
          MYSQL_ROOT_PASSWORD: example
      - image: redis
    steps:
      - checkout
      - run: bundle install --path vendor/bundle
      - run: bundle exec rails db:create db:schema:load db:migrate
      - run: bundle exec rspec

    