# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

production:
  secret_key_base: secret_key_base_for_staging_tries_to_be_a_bit_longer_than_before_just_to_make_sure_its_useful
  s3:                                                                              
    aws_access_key_id: ____c                                                       
    aws_secret_access_key: ____                                                    
    attachments_bucket: production

staging:                                                                           
  secret_key_base: secret_key_base_for_staging_tries_to_be_a_bit_longer_than_before_just_to_make_sure_its_useful
  s3:                                                                              
    aws_access_key_id: ____c                                                       
    aws_secret_access_key: ____                                                    
    attachments_bucket: staging   
